name: ski_rental
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  material_symbols_icons: ^4.2815.0
  carousel_slider_plus: ^7.1.0
  calendar_date_picker2: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  fonts:
    - family: Montserrat
      fonts:
        - asset: asset\fonts\Montserrat-400.ttf
        - asset: asset\fonts\Montserrat-400Italic.ttf
          style: italic
        - asset: asset\fonts\Montserrat-100.ttf
          weight: 100
        - asset: asset\fonts\Montserrat-100Italic.ttf
          weight: 100
          style: italic
        - asset: asset\fonts\Montserrat-200.ttf
          weight: 200
        - asset: asset\fonts\Montserrat-200Italic.ttf
          weight: 200
          style: italic
        - asset: asset\fonts\Montserrat-300.ttf
          weight: 300
        - asset: asset\fonts\Montserrat-300Italic.ttf
          weight: 300
          style: italic
        - asset: asset\fonts\Montserrat-500.ttf
          weight: 500
        - asset: asset\fonts\Montserrat-500Italic.ttf
          weight: 500
          style: italic
        - asset: asset\fonts\Montserrat-600.ttf
          weight: 600
        - asset: asset\fonts\Montserrat-600Italic.ttf
          weight: 600
          style: italic
        - asset: asset\fonts\Montserrat-700.ttf
          weight: 700
        - asset: asset\fonts\Montserrat-700Italic.ttf
          weight: 700
          style: italic
        - asset: asset\fonts\Montserrat-800.ttf
          weight: 800
        - asset: asset\fonts\Montserrat-800Italic.ttf
          weight: 800
          style: italic
        - asset: asset\fonts\Montserrat-900.ttf
          weight: 900
        - asset: asset\fonts\Montserrat-900Italic.ttf
          weight: 900
          style: italic
